config/routes.rb
Rails.application.routes.draw do

  resources :photos
  get 'my_lenta', to: 'home#index'
  scope :photos do
    resources :likes, only: [:new, :create, :destroy]
  end

  devise_for :users
  resources :users do
    member do
      get :following, :followers
    end
  end

  scope :photos do
    resources :comments, only: [:new, :create, :destroy]
  end

  root 'photos#index'

  resources :relationships,       only: [:create, :destroy]

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
       user ||= User.new # guest user (not logged in)

       can :create, Photo
       can :read, Photo
       can :update, Photo, :user_id=>user.id
       can :destroy, Photo, :user_id=>user.id



    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :photo
end

app/models/like.rb
class Like < ActiveRecord::Base
  belongs_to :photo
  belongs_to :user
end

app/models/photo.rb
class Photo < ActiveRecord::Base

  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy

  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/

  validates :image, presence: true

end

app/models/relationship.rb
class Relationship < ActiveRecord::Base
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
  validates :follower_id, presence: true
  validates :followed_id, presence: true  
end

app/models/user.rb
class User < ActiveRecord::Base

  has_many :photos, dependent: :destroy
  has_many :likes, dependent: :destroy
    has_many :active_relationships,  class_name:  "Relationship",
                                     foreign_key: "follower_id",
                                     dependent:   :destroy
    has_many :passive_relationships, class_name:  "Relationship",
                                     foreign_key: "followed_id",
                                     dependent:   :destroy
    has_many :following, through: :active_relationships,  source: :followed
    has_many :followers, through: :passive_relationships, source: :follower

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

         # Follows a user.
           def follow(other_user)
             following << other_user
           end

           # Unfollows a user.
           def unfollow(other_user)
             following.delete(other_user)
           end

           # Returns true if the current user is following the other user.
           def following?(other_user)
             following.include?(other_user)
           end

          #  def like?(photo_id)
           #
          #    if Like.find_by(user_id: self.id, photo_id: photo_id) not nil
          #       true
          #    else
          #       false
          #    end
           #
          #  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_url, :alert => exception.message
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @comment = Comment.new(comment_params)
    @comment.user_id = current_user.id
    if @comment.save
      flash[:success] = 'YES'
      redirect_to :back
    else
      flash[:error] = 'nope'
      redirect_to :back
    end
  end


    private

    def comment_params
      params.require(:comment).permit(:content, :photo_id)
    end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!
  def index

    @people = current_user.following
    @people.map do |person|
       person.id
     end


     @photos = Photo.where(user_id: @people)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

    def create
      @like = Like.new
      @like.user_id = current_user.id
      @like.photo_id = params[:photo_id]
      if @like.save
            flash[:success] = "LIKE добавлен"
            redirect_to "/photos/#{@like.photo_id}"
      end
    end

    def destroy
      @like =  Like.destroy(params[:id])
      redirect_to "/photos/#{@like.photo_id}"

    end


end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :destroy, :show]
  def index
    @photos = Photo.all
  end

  def show

    @photo = Photo.find(params[:id])
    authorize! :read, @photo
  end

  def edit

    @photo = Photo.find(params[:id])
    authorize! :update, @photo
  end

  def new
    @photo = Photo.new
  end

  def create
    @photo = Photo.new(photo_params)
    @photo.user_id = current_user.id
    if @photo.save
      flash[:success] = "Фото загружено"
      redirect_to root_path
    else
      render 'new'
    end
  end

  def destroy
    authorize! :update, @photo
    Photo.find(params[:id]).destroy
    flash[:success] = "Фото успешно удалена!"
    redirect_to root_path
  end

  def update
    @photo = Photo.find(params[:id])
    if @photo.update_attributes(photo_params)
      flash[:success] = "Фото отредактирован"
      redirect_to root_path
    else
      render 'edit'
    end
  end


          private

            def photo_params
              params.require(:photo).permit(:image, :user_id)
            end


end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  def create
    user = User.find(params[:followed_id])
    current_user.follow(user)
    redirect_to :back
  end

  def destroy
    user = Relationship.find(params[:id]).followed
    current_user.unfollow(user)
    redirect_to :back
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/views/comments/create.html.erb
<h1>Comments#create</h1>
<p>Find me in app/views/comments/create.html.erb</p>

app/views/home/index.html.erb
<% @photos.each do |photo| %>
<li>
  <%= image_tag photo.image.url(:medium) %>
  <% if can? :update, photo%>
   <%= link_to "Редактировать", edit_photo_path(photo)%>-
  <% end %>

  <% if can? :destroy, photo%>
   <%= link_to "Удалить", photo, method: :delete, data: { confirm: "Are you sure?" }%>-
  <% end %>

   <%= link_to "Просмотр", photo%>
</li>
<li><%= photo.user.id %></li>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Homework26</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <nav class="navbar navbar-default">
    <div class="container-fluid">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/">ИнстаграМ</a>
      </div>

      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
          <li><%= link_to "Лента", my_lenta_path %></li>
          <% if current_user %>
          <li><%= link_to "Мой профиль", edit_user_registration_path(current_user), class: 'navbar-link' %></li>
          <li><%= link_to "Log Out", destroy_user_session_path, method: :delete %></li>
          <li><%= link_to "Добавить фоточку", new_photo_path %></li>
            <% else %>
              <li><%= link_to "Login", new_user_session_path %></li>
              <li><%= link_to "Sign up", new_user_registration_path %></li>
            <% end %>
        </ul>
      </div>
    </div>
  </nav>

  <% flash.each do |message_type, message| %>
    <div class="alert alert-<%= message_type %>"><%= message %></div>
  <% end %>
<%= yield %>
<%= debug(params) if Rails.env.development? %>
</body>
</html>

app/views/likes/create.html.erb
<h1>Likes#create</h1>
<p>Find me in app/views/likes/create.html.erb</p>

app/views/likes/destroy.html.erb
<h1>Likes#destroy</h1>
<p>Find me in app/views/likes/destroy.html.erb</p>

app/views/likes/new.html.erb
<h1>Likes#new</h1>
<p>Find me in app/views/likes/new.html.erb</p>

app/views/photos/_form.html.erb
<%= form_for @photo, html: { multipart: true } do |form| %>

  <%= render 'shared/error_messages', object: form.object %>
  <%= form.file_field :image %>
  <%= form.hidden_field :user_id, :value => current_user.id %>
  <%= form.submit "Сохранить" %>
  
<% end %>

app/views/photos/_photo.html.erb
<li>
  <%= image_tag photo.image.url(:medium) %>
  <% if can? :update, photo%>
   <%= link_to "Редактировать", edit_photo_path(photo)%>-
  <% end %>

  <% if can? :destroy, photo%>
   <%= link_to "Удалить", photo, method: :delete, data: { confirm: "Are you sure?" }%>-
  <% end %>

   <%= link_to "Просмотр", photo%>
</li>
<li><%= photo.user.id %></li>

app/views/photos/edit.html.erb
<h1>Редактирование фото</h1>


<%= render 'form'%>

app/views/photos/index.html.erb
<h1>Фото</h1>
<ul>
<%= render @photos %>
</ul>

app/views/photos/new.html.erb
<h1>Добавление фото</h1>

<%= render 'form'%>

app/views/photos/show.html.erb
<h1>Просмотр фото</h1>
<%= image_tag @photo.image.url(:medium) %>

<ul>
  <li><%= @photo.user.following.count %> - юзер подписан</li>
  <li><%= @photo.user.followers.count %> - на юзера подписались:</li>
  <li><%= @photo.likes.count %> - фоточку лайкнули:</li>
</ul>

<% if @like = Like.find_by(user_id: current_user.id, photo_id: @photo.id) %>
  <%= link_to( "UNLIKE", @like, class: "btn btn-primary", method: :delete, data: { confirm: "Are you sure?"}) %>
<% else %>
  <%= form_for(:like, url: likes_path) do |f| %>
  <%= hidden_field_tag :photo_id, @photo.id %>
  <%= f.submit "LIKE", class: "btn" %>
  <% end %>
<% end %>


<hr>

  <% if current_user.following?(@photo.user) %>

      <%= form_for(current_user.active_relationships.find_by(followed_id: @photo.user.id),
                 html: { method: :delete }) do |f| %>
      <%= f.submit "Unfollow", class: "btn" %>
      <% end %>

  <% else %>

    <%= form_for(current_user.active_relationships.build) do |f| %>
      <div><%= hidden_field_tag :followed_id, @photo.user.id %></div>
      <%= f.submit "Follow", class: "btn btn-primary" %>
    <% end %>

  <% end %>


<% if @photo.comments.any? %>
  <% @photo.comments.each do |c| %>
    <hr> <%= c.content %> 
  <% end %>
<% end %>

<%= form_for @comment = Comment.new do |f| %>
<%= f.text_area :content %>
<%= f.hidden_field :photo_id, :value => @photo.id %>
<%= f.submit "Сохранить" %>
<% end %>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>